name: Slot Machine Spin

on:
  repository_dispatch:
    types: [remote_spin] # Questo intercetta il segnale da Vercel

jobs:
  spin:
    runs-on: ubuntu-latest
    # Permessi necessari per permettere alla Action di scrivere nella repo
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Execute Slot Script
        run: python GenerateSlot.py
        
      - name: Purge GitHub Cache
        run: |
          curl -X PURGE https://camo.githubusercontent.com/$(echo -n "https://raw.githubusercontent.com/${{ github.repository }}/main/slot.svg" | openssl sha1 | sed 's/^.* //')

      - name: Update README
        run: |
          # Genera un numero unico basato sui secondi
          TIMESTAMP=$(date +%s)
          # Cerca il link della slot e cambia il valore dopo v=
          sed -i "s/slot.svg?v=[0-9]*/slot.svg?v=${TIMESTAMP}/g" README.md
          
      - name: Commit and Push
        run: |
          git config --global user.name "SlotBot"
          git config --global user.email "bot@github.com"
          git add slot.svg README.md
          # Se non ci sono modifiche, non fallire
          git commit -m "🎰 Spin $TIMESTAMP" || exit 0
          git push
          
